drive/urls.py
from django.conf.urls.defaults import patterns, url
from django.contrib.auth.decorators import login_required

from .views import *

urlpatterns = patterns('drive.views',
    url(r'^$', login_required(RecentView.as_view()), name='recent'),
    url(r'^category/(?P<name>\w+)/$', login_required(CategoryView.as_view()), name='category'),
    url(r'^add/$', login_required(AddView.as_view()), name='add'),
    url(r'^edit/(?P<pk>\w+)/$', login_required(EditView.as_view()), name='edit'),
    url(r'^delete/(?P<pk>\w+)/$', login_required(DeleteView.as_view()), name='delete'),
    url(r'^file/(?P<pk>\w+)/$', login_required(FileView.as_view()), name='file'),
    url(r'^all/$', login_required(AllView.as_view()), name='all'),
    url(r'^changelog/$', ChangelogView.as_view(), name='changelog'),
    url(r'^search/$', login_required(SearchView.as_view()), name='search'),
)

gilgidrive/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from .settings import DEBUG, MEDIA_ROOT, STATIC_ROOT

admin.autodiscover()

urlpatterns = patterns('',
    # drive app
    url(r'^', include('drive.urls')),

    # auth-related URLs
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/loggedout/'}, name='logout'),
    url(r'^switchuser/$', 'django.contrib.auth.views.logout_then_login', name='switchuser'),
    url(r'^loggedout/$', 'gilgidrive.views.loggedout'),
    url(r'^changepassword/$', 'django.contrib.auth.views.password_change', name='changepassword'),
    url(r'^passwordchanged/$', 'django.contrib.auth.views.password_change_done'),
    
    # password reset urls (not working)
    #url(r'^resetpassword/$', 'django.contrib.auth.views.password_reset'),
    #url(r'^resetsent/$', 'django.contrib.auth.views.password_reset_done'),
    #url(r'^setnewpassword/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm'),
    #url(r'^setnewpassword/[0-9A-Za-z]+-.+/$', 'django.contrib.auth.views.password_reset_confirm'),
    #url(r'^resetcomplete/$', 'django.contrib.auth.views.password_reset_complete'),

    # admin docs
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # admin
    url(r'^admin/', include(admin.site.urls)),
)

# DEV ONLY!!!!!!!!!!
#
# this magic code snippet allows the dev server to serve anything in media/ and static/
if DEBUG:
    urlpatterns += patterns('',
        #url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': MEDIA_ROOT,}),
        #url(r'^static/admin/(?P<path>.*)$', 'django.views.static.serve', {'document_root': STATIC_ROOT + '/admin/',}),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': STATIC_ROOT,})
                            )

gilgitorrents/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from .settings import DEBUG, MEDIA_ROOT, STATIC_ROOT

admin.autodiscover()

urlpatterns = patterns('',
    # torrents app
    url(r'^', include('torrents.urls')),

    # auth-related URLs
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/loggedout/'}, name='logout'),
    url(r'^switchuser/$', 'django.contrib.auth.views.logout_then_login', name='switchuser'),
    url(r'^loggedout/$', 'gilgitorrents.views.loggedout'),
    url(r'^changepassword/$', 'django.contrib.auth.views.password_change', name='changepassword'),
    url(r'^passwordchanged/$', 'django.contrib.auth.views.password_change_done'),
    
    # password reset urls (not working)
    #url(r'^resetpassword/$', 'django.contrib.auth.views.password_reset'),
    #url(r'^resetsent/$', 'django.contrib.auth.views.password_reset_done'),
    #url(r'^setnewpassword/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm'),
    #url(r'^setnewpassword/[0-9A-Za-z]+-.+/$', 'django.contrib.auth.views.password_reset_confirm'),
    #url(r'^resetcomplete/$', 'django.contrib.auth.views.password_reset_complete'),

    # admin docs
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # admin
    url(r'^admin/', include(admin.site.urls)),
)

# DEV ONLY!!!!!!!!!!
#
# this magic code snippet allows the dev server to serve anything in media/ and static/
if DEBUG:
    urlpatterns += patterns('',
        #url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': MEDIA_ROOT,}),
        #url(r'^static/admin/(?P<path>.*)$', 'django.views.static.serve', {'document_root': STATIC_ROOT + '/admin/',}),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': STATIC_ROOT,})
                            )

drive/models.py
import binascii, urllib, re

from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse

from .random_primary import RandomPrimaryIdModel

class Category(models.Model):
    name = models.CharField(max_length=32)

    def __unicode__(self):
        return self.name

def magnet_validator(value):
    if value:
        pieces = value.split('&')
        for piece in pieces:
            if 'tr=' in piece:
                if piece != 'tr=udp%3a%2f%2ftracker.gilgi.org%3a6969%2fannounce':
                    raise ValidationError(u'torrent must use only udp://tracker.gilgi.org:6969/announce')
            
def get_info_hash(magnet_link):
    return magnet_link[20:60]

def get_scrape_url(info_hash):
    return 'http://tracker.gilgi.org:6969/scrape?info_hash=' + urllib.quote_plus(binascii.a2b_hex(info_hash))

class File(RandomPrimaryIdModel):
    user = models.ForeignKey(User)
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    description = models.TextField()
    added = models.DateTimeField(auto_now_add=True)
    magnet_link = models.CharField(max_length=256, validators=[magnet_validator], blank=True, null=True)
    direct_link = models.CharField(max_length=256, blank=True, null=True)

    class Meta:
        ordering = ['-added']
    
    def get_info(self):
        if not self.magnet_link:
            return {'seeders': 0, 'leechers': 0, 'downloads': 0}
        response = urllib.urlopen(get_scrape_url(get_info_hash(self.magnet_link)))
        match = re.match( r'.*completei(.*)e10:downloadedi(.*)e10:incompletei(.*)eeee', response.read(), re.S|re.M|re.I)
        if match:
            #print 'match succeeded'
            #response = urllib.urlopen(get_scrape_url(get_info_hash(self.magnet_link)))
            #print response.read()
            return {'seeders': match.group(1), 'leechers': match.group(3), 'downloads': match.group(2)}
        #print 'match failed'
        #response = urllib.urlopen(get_scrape_url(get_info_hash(self.magnet_link)))
        #print response.read()
        return {'seeders': 0, 'leechers': 0, 'downloads': 0}

    def get_absolute_url(self):
        return reverse('file', kwargs={'pk': self.pk})
        
    def __unicode__(self):
        return self.title

drive/forms.py
from django import forms
from .models import File

class FileForm(forms.ModelForm):
    class Meta:
        model = File
        exclude = ('id', 'user', 'added',)
        
class SearchForm(forms.Form):
    query = forms.CharField(max_length=64, required=False, widget=forms.TextInput(attrs={'class': 'search-query',
                                                                                         'placeholder': 'Search Files',
                                                                                         'id': 'search-input'}))

drive/views.py
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.edit import DeleteView as GenericDeleteView
from django.shortcuts import get_object_or_404
from django.http import Http404, HttpResponseRedirect
from django.core.urlresolvers import reverse_lazy

from .models import Category, File
from .forms import FileForm, SearchForm
from .search import normalize_query, get_query

# context needed by all views (e.g., because navbar)
def common_context(view_instance):
    context = {}
    # needed for dropdown
    context['categories'] = Category.objects.all()
    context['search_form'] = SearchForm()
    return context

class AllView(ListView):
    def get_queryset(self):
        files = File.objects.all()
        for file in files:
            file.info = file.get_info()
        return files
        
    def get_context_data(self, **kwargs):
        context = super(AllView, self).get_context_data(**kwargs)
        context = dict(context.items() + common_context(self).items())
        context['page_title'] = 'all files'
        context['all_active'] = 'active'
        context['categories_active'] = 'active'
        return context

class RecentView(ListView):
    def get_queryset(self):
        files = File.objects.all()[:20]
        for file in files:
            file.info = file.get_info()
        return files

    def get_context_data(self, **kwargs):
        context = super(RecentView, self).get_context_data(**kwargs)
        context = dict(context.items() + common_context(self).items())
        context['page_title'] = 'recent files'
        context['recent_active'] = 'active'
        return context

class CategoryView(ListView):
    def get_queryset(self):
        category = get_object_or_404(Category, name=self.kwargs['name'])
        files = File.objects.filter(category=category)
        for file in files:
            file.info = file.get_info()
        return files

    def get_context_data(self, **kwargs):
        context = super(CategoryView, self).get_context_data(**kwargs)
        context = dict(context.items() + common_context(self).items())
        context['page_title'] = 'category: ' + self.kwargs['name']
        context['categories_active'] = 'active'
        for category in context['categories']:
            if category.name == self.kwargs['name']:
                category.active = 'active'
        return context

class SearchView(ListView):
    template_name = 'drive/file_list.html'

    def get_queryset(self):
        query_string = ''
        files = None
        if ('query' in self.request.GET) and self.request.GET['query'].strip():
            query_string = self.request.GET['query']
            file_query = get_query(query_string, ['title', 'description', 'user__username', 'category__name'],)
            files = File.objects.filter(file_query)
        if files:
            for file in files:
                file.info = file.get_info()
        return files
        
    def get_context_data(self, **kwargs):
        context = super(SearchView, self).get_context_data(**kwargs)
        context = dict(context.items() + common_context(self).items())
        context['page_title'] = 'Search Results'
        context['search'] = True
        return context
        
class AddView(CreateView):
    form_class = FileForm
    template_name = 'drive/file_form.html'
    
    def get_context_data(self, **kwargs):
        context = super(AddView, self).get_context_data(**kwargs)
        context = dict(context.items() + common_context(self).items())
        context['add_active'] = 'active'
        context['add_or_edit'] = 'add'
        context['add_or_save'] = 'add'
        return context
    
    #def post(self, request, *args, **kwargs):
    #    super(AddView, self).post(request, *args, **kwargs)
    #    print 'poast'
    #    form = request.form
    #    context = self.get_context_data(form=form)
    #    return HttpResponseRedirect(self.get_success_url())

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

class EditView(UpdateView):
    form_class = FileForm
    model = File
    template_name = 'drive/file_form.html'
    
    def get(self, request, *args, **kwargs):
        file = get_object_or_404(File, pk=self.kwargs['pk'])
        if file.user != self.request.user:
            raise Http404
        return super(EditView, self).get(request, *args, **kwargs)
        
    def get_context_data(self, **kwargs):
        context = super(EditView, self).get_context_data(**kwargs)
        context = dict(context.items() + common_context(self).items())
        context['add_or_edit'] = 'edit'
        context['add_or_save'] = 'save'
        return context

class DeleteView(GenericDeleteView):
    model = File
    success_url = reverse_lazy('recent')
    
    def get(self, request, *args, **kwargs):
        file = get_object_or_404(File, pk=self.kwargs['pk'])
        if file.user != self.request.user:
            raise Http404
        return super(DeleteView, self).get(request, *args, **kwargs)

class FileView(DetailView):
    model = File
    
    def get_context_data(self, **kwargs):
        context = super(FileView, self).get_context_data(**kwargs)
        context = dict(context.items() + common_context(self).items())
        self.object.info = self.object.get_info()
        if self.object.user == self.request.user:
            context['owned'] = True
        return context
        
class ChangelogView(TemplateView):
    template_name = 'changelog.html'
    
    def get_context_data(self, **kwargs):
        context = super(ChangelogView, self).get_context_data(**kwargs)
        context = dict(context.items() + common_context(self).items())
        context['changelog_active'] = 'active'
        return context

drive/templates/drive/file_confirm_delete.html
{% extends "base.html" %}

{% block title %}Confirm Delete: {{ object.title|title }}{% endblock %}

{% block content %}

<h1>Confirm Delete: {{ object.title|title }}</h1>

<p>Are you sure you want to delete this file? This action cannot be undone!</p>

<div class="btn-group">
  <a class="btn btn-primary" href="{% url 'file' pk=object.pk %}">Go Back</a>
  <form action="" method="post">{% csrf_token %}
  <input class="btn btn-danger" type="submit" value="Delete File" />
  </form>
</div>

{% endblock %}

drive/templates/drive/file_detail.html
{% extends "base.html" %}

{% block title %}{{ object.title|title }}{% endblock %}

{% block content %}

<h1>{{ object.title }}
{% if owned %}
<small style="float:right;">
<div class="btn-group">
  <a class="btn btn-primary" href="{% url 'edit' pk=object.pk %}">Edit File</a>
  <a class="btn btn-danger" href="{% url 'delete' pk=object.pk %}">Delete File</a>
</div>
</small>
{% endif %}
</h1>

<div class="btn-group">
  {% if object.magnet_link %}
  <a class="btn btn-success" href="{{ object.magnet_link }}">Magnet Link</a>
  {% endif %}
  {% if object.direct_link %}
  <a class="btn btn-success" href="{{ object.direct_link }}">Direct Link</a>
  {% endif %}
</div>

<p class="description">{{ object.description }}</p>

<table class="table table-bordered table-striped">
  <tr>
    <th>Title</th>
    <th>{{ object.title }}</th>
  </tr>
  <tr>
    <th>Added By</th>
    <td>{{ object.user }}</td>
  </tr>
  <tr>
    <th>Added</th>
    <td>{{ object.added|date:"Y-m-d H:i:s" }}</td>
  </tr>
  <tr>
    <th>Seeders</th>
    <td>{{ object.info.seeders }}</td>
  </tr>
  <tr>
    <th>Leechers</th>
    <td>{{ object.info.leechers }}</td>
  </tr>
  <tr>
    <th>Downloads</th>
    <td>{{ object.info.downloads }}</td>
  </tr>
</table>

   <div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'gilgidrive'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
    
    

{% endblock %}

drive/templates/drive/file_form.html
{% extends "base.html" %}

{% block title %}{{ add_or_edit|title }} File{% endblock %}

{% block content %}

<h1>{{ add_or_edit|title }} File</h1>

<form action="" method="post">{% csrf_token %}
    {{ form.non_field_errors }}
    {{ form.errors }}
    <div class="fieldWrapper">
        {{ form.title.errors }}
        <label for="id_title">Title:</label>
        {{ form.title }}
    </div>
    <div class="fieldWrapper">
        {{ form.category.errors }}
        <label for="id_message">Category:</label>
        {{ form.category }}
    </div>
    <div class="fieldWrapper">
        {{ form.description.errors }}
        <label for="id_description">Description:</label>
        {{ form.description }}
    </div>
    <div class="fieldWrapper">
        {{ form.direct_link.errors }}
        <label for="id_direct_link">Direct link:</label>
        <span>
        {{ form.direct_link }}
        <input type="dropbox-chooser" name="selected-file" id="db-chooser"/>
        <script type="text/javascript">
            document.getElementById("db-chooser").addEventListener("DbxChooserSuccess",
                function(e) {
                    document.getElementById("id_direct_link").value = e.files[0].link;
                }, false);
        </script>
        </span>
    </div>
    <div class="fieldWrapper">
        {{ form.magnet_link.errors }}
        <label for="id_magnet_link">Magnet link:</label>
        {{ form.magnet_link }}
    </div>
    <input class="btn btn-primary" type="submit" value="{{ add_or_save|title }} File" />
</form>

{% endblock %}

drive/templates/drive/file_list.html
{% extends "base.html" %}

{% block title %}{{ page_title|title }}{% endblock %}

{% block content %}

<h1>{{ page_title|title}}</h1>

{% if file_list %}
<table id="filetable" class="table table-bordered table-striped tablesorter">
  <thead>
    <tr>
      <th>Name</th>
      <th>Added By</th>
      <th>Added</th>
      <th>Direct Link</th>
      <th>Magnet Link</th>
      <th>Seeders</th>
      <th>Leechers</th>
      <th>Downloads</th>
    </tr>
  </thead>
  <tbody>
    {% for file in file_list %}
    <tr>
      <td><a href="{% url 'file' pk=file.pk %}">{{ file.title }}</td>
      <td>{{ file.user.username }}</td>
      <td>{{ file.added|date:"Y-m-d H:i:s" }}</td>
      <td>
        {% if file.direct_link %}
        <a class="btn btn-success btn-mini" href="{{ file.direct_link }}">Download</a>
        {% else %}
        <a class="btn btn-danger btn-mini disabled" href="#">Unavailable</a>
        {% endif %}
      </td>
      <td>
        {% if file.magnet_link %}
        <a class="btn btn-success btn-mini" href="{{ file.magnet_link }}">Download</a>
        {% else %}
        <a class="btn btn-danger btn-mini disabled" href="#">Unavailable</a>
        {% endif %}
      </td>
      <td>{{ file.info.seeders }}</td>
      <td>{{ file.info.leechers }}</td>
      <td>{{ file.info.downloads }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
{% if search %}
<p>No files matching your search query were found.</p>
{% else %}
<p>There are no files yet.</p>
{% endif %}
{% endif %}

<script>
$(document).ready(function() 
    { 
        $("#filetable").tablesorter( {sortList: [[2,1]]} ); 
    } 
); 
</script>

{% endblock %}